# Generated by Django 2.2.15 on 2020-08-10 17:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=False)),
                ('issue_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('from_client', models.CharField(blank=True, max_length=50, null=True)),
                ('for_client', models.CharField(blank=True, max_length=50, null=True)),
                ('file_data', models.FileField(upload_to='invoice_digitization/data')),
            ],
            options={
                'managed': True,
                'db_table': 'invoice',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('unit_price', models.FloatField(default=0.0)),
                ('amount', models.FloatField(default=0.0)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice_digitization.Invoice')),
            ],
            options={
                'managed': True,
                'db_table': 'product',
            },
        ),
    ]
